macro(try_implement_json_field)
    set(options "")
    set(single_args JSON_DATA PARAMETER_OUT)
    set(multi_args KEYS)
    cmake_parse_arguments(ARGS "${options}" "${single_args}" "${multi_args}" ${ARGN})

    string(JSON var ERROR_VARIABLE var_found GET ${ARGS_JSON_DATA} ${ARGS_KEYS})
    if(${var_found} MATCHES "NOTFOUND")
        list(GET ARGS_KEYS -1 last_key)
        message(STATUS "Using custom key [${last_key}=${var}]")
        set(nf_test_filename_suffix ${nf_test_filename_suffix}_${var})
        set(${ARGS_PARAMETER_OUT} ${var})
    endif()
endmacro()
